### ISSUE TITLE
🗃️ Archive Pages - Products Epic

### ISSUE THREAD

**Issue by Harry-Ross** [SSWConsulting/SSW.Website-v1-archive#20]
After approval for the `/Events` batch of pages (https://github.com/SSWConsulting/SSW.Website-v1-Progress/issues/15), proceed with this issue.

```[tasklist]
### Tasks
- [x] Archive products pages (i.e. AccessReporter, AgileTemplate) that are already commented out on the `WHITELIST` variable.
- [ ] https://github.com/SSWConsulting/SSW.Website-v1-Progress/issues/30
- [ ] https://github.com/SSWConsulting/SSW.Website-v1-Progress/issues/31
- [ ] https://github.com/SSWConsulting/SSW.Website-v1-Progress/issues/32
- [ ] https://github.com/SSWConsulting/SSW.Website-v1-Progress/issues/33
- [x] Fix any broken navbar links throughout these pages
- [x] Get Test Pleased by Matt W
```
